# Generated by Django 3.0.7 on 2020-06-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('submitter', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(verbose_name='steam store page')),
                ('price', models.FloatField()),
                ('ttb', models.FloatField(verbose_name='TTB')),
                ('thoughts', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenrePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recs.Game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recs.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(through='recs.GameGenrePosition', to='recs.Genre', verbose_name='genres'),
        ),
    ]
