# Generated by Django 3.0.7 on 2020-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='thoughts',
            field=models.TextField(max_length=1000),
        ),
    ]
